In [1]:
import pandas as pd

In [4]:

data = {
    'City': ['Pune', 'Mumbai', 'Delhi', 'Pune', 'Mumbai'],
    'Product': ['A', 'B', 'A', 'C', 'B'],
    'Sales': [100, 200, 150, 300, 250],
    'Quantity': [2, 3, 1, 5, 4]
}

df = pd.DataFrame(data)
df

     City Product  Sales  Quantity
0    Pune       A    100         2
1  Mumbai       B    200         3
2   Delhi       A    150         1
3    Pune       C    300         5
4  Mumbai       B    250         4

In [5]:
total_sales = df['Sales'].sum()
total_sales

np.int64(1000)

In [6]:
city_wise_sales = df.groupby('City')['Sales'].sum()
city_wise_sales

City
Delhi     150
Mumbai    450
Pune      400
Name: Sales, dtype: int64

In [7]:
df['revenue'] = df['Sales'] * df['Quantity']
df

     City Product  Sales  Quantity  revenue
0    Pune       A    100         2      200
1  Mumbai       B    200         3      600
2   Delhi       A    150         1      150
3    Pune       C    300         5     1500
4  Mumbai       B    250         4     1000

In [8]:
top_product = df.groupby('Product')['revenue'].sum()
top_product

Product
A     350
B    1600
C    1500
Name: revenue, dtype: int64

In [11]:
top_product.idxmax()

'B'

In [13]:
df.groupby('City')['revenue'].sum()idxmax()

City        0
Product     3
Sales       3
Quantity    3
revenue     3
dtype: int64