In [1]:
# import libraries

import pandas as pd
from sqlalchemy import create_engine

In [3]:
# load all files

sales = pd.read_excel('sales_data.xlsx')
order = pd.read_csv('orders_data.csv')
emp = pd.read_json('employee_data.json')

# basic data understanding

In [4]:
sales.head()
sales.tail()
sales.info()
sales.describe()
sales.shape
sales.columns
sales.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       5 non-null      int64
 1   Order_Date     5 non-null      object
 2   Customer_Name  5 non-null      object
 3   Region         5 non-null      object
 4   Product        5 non-null      object
 5   Category       5 non-null      object
 6   Quantity       5 non-null      int64
 7   Price          5 non-null      int64
 8   Discount       5 non-null      int64
 9   Payment_Mode   5 non-null      object
dtypes: int64(4), object(6)
memory usage: 532.0+ bytes

Order_ID         0
Order_Date       0
Customer_Name    0
Region           0
Product          0
Category         0
Quantity         0
Price            0
Discount         0
Payment_Mode     0
dtype: int64

In [5]:
order.head()
order.tail()
order.info()
order.describe()
order.shape
order.columns
order.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5 non-null      int64
 1   order_date     5 non-null      object
 2   customer_id    5 non-null      object
 3   product        5 non-null      object
 4   category       5 non-null      object
 5   price          5 non-null      int64
 6   quantity       5 non-null      int64
 7   city           5 non-null      object
 8   delivery_days  5 non-null      int64
dtypes: int64(4), object(5)
memory usage: 492.0+ bytes

order_id         0
order_date       0
customer_id      0
product          0
category         0
price            0
quantity         0
city             0
delivery_days    0
dtype: int64

In [6]:
emp.head()
emp.tail()
emp.info()
emp.describe()
emp.shape
emp.columns
emp.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      4 non-null      int64
 1   name        4 non-null      object
 2   department  4 non-null      object
 3   salary      4 non-null      int64
 4   experience  4 non-null      int64
 5   city        4 non-null      object
dtypes: int64(3), object(3)
memory usage: 324.0+ bytes

emp_id        0
name          0
department    0
salary        0
experience    0
city          0
dtype: int64

# Data cleaning

In [7]:
# Remove duplicates

sales.drop_duplicates(inplace=True)
order.drop_duplicates(inplace=True)
emp.drop_duplicates(inplace=True)

In [8]:
# handling missing values

sales.fillna(0,inplace=True)
order.fillna(method='ffill',inplace=True)
emp.fillna(emp['salary'].mean(),inplace=True)

C:\Users\Acer\AppData\Local\Temp\ipykernel_14860\567990599.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  order.fillna(method='ffill',inplace=True)

In [9]:
# Change data types

sales['Order_Date'] = pd.to_datetime(sales['Order_Date'])
sales.info()



order['order_date']= pd.to_datetime(order['order_date'])
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       5 non-null      int64
 1   Order_Date     5 non-null      datetime64[ns]
 2   Customer_Name  5 non-null      object
 3   Region         5 non-null      object
 4   Product        5 non-null      object
 5   Category       5 non-null      object
 6   Quantity       5 non-null      int64
 7   Price          5 non-null      int64
 8   Discount       5 non-null      int64
 9   Payment_Mode   5 non-null      object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 532.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5 non-null      int64
 1   order_date     5 non-null      datetime64[ns]
 2   customer_id    5 non-null      object
 3   product        5 non-null      object
 4   category       5 non-null      object
 5   price          5 non-null      int64
 6   quantity       5 non-null      int64
 7   city           5 non-null      object
 8   delivery_days  5 non-null      int64
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 492.0+ bytes

In [10]:
#Feature engineering 

sales.head()

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Price,Discount,Payment_Mode
0,1001,2024-01-05,Amit Sharma,West,Laptop,Electronics,2,55000,5,UPI
1,1002,2024-01-06,Priya Verma,North,Phone,Electronics,1,30000,10,Credit Card
2,1003,2024-01-07,Rahul Jain,South,Table,Furniture,3,8000,0,Cash
3,1004,2024-01-08,Sneha Patil,East,Chair,Furniture,5,2000,5,UPI
4,1005,2024-01-09,Arjun Rao,West,Monitor,Electronics,2,15000,8,Debit Card

In [11]:
sales["Total_Amount"] = (
    sales["Quantity"] *
    sales["Price"] *
    (1 - sales["Discount"] / 100)
)

In [12]:
order.head()

,order_id,order_date,customer_id,product,category,price,quantity,city,delivery_days
0,5001,2024-02-01,C001,Laptop,Electronics,55000,1,Nagpur,3
1,5002,2024-02-02,C002,Phone,Electronics,30000,2,Mumbai,5
2,5003,2024-02-03,C003,Shoes,Fashion,4000,3,Pune,4
3,5004,2024-02-04,C001,Watch,Fashion,7000,1,Nagpur,2
4,5005,2024-02-05,C004,Tablet,Electronics,25000,1,Delhi,6

In [13]:
order["Revenue"] = order["price"] * order["quantity"]

In [14]:
# prders dataset
order.head()

,order_id,order_date,customer_id,product,category,price,quantity,city,delivery_days,Revenue
0,5001,2024-02-01,C001,Laptop,Electronics,55000,1,Nagpur,3,55000
1,5002,2024-02-02,C002,Phone,Electronics,30000,2,Mumbai,5,60000
2,5003,2024-02-03,C003,Shoes,Fashion,4000,3,Pune,4,12000
3,5004,2024-02-04,C001,Watch,Fashion,7000,1,Nagpur,2,7000
4,5005,2024-02-05,C004,Tablet,Electronics,25000,1,Delhi,6,25000

In [15]:
# emp dataset

emp.head()

   emp_id         name department  salary  experience    city
0       1  Amit Sharma         HR   45000           3  Nagpur
1       2  Priya Verma         IT   75000           5  Mumbai
2       3   Rahul Jain    Finance   65000           4    Pune
3       4  Sneha Patil         IT   82000           6  Nagpur

# EDA

In [18]:
sales.head()

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Price,Discount,Payment_Mode,Total_Amount
0,1001,2024-01-05,Amit Sharma,West,Laptop,Electronics,2,55000,5,UPI,104500.0
1,1002,2024-01-06,Priya Verma,North,Phone,Electronics,1,30000,10,Credit Card,27000.0
2,1003,2024-01-07,Rahul Jain,South,Table,Furniture,3,8000,0,Cash,24000.0
3,1004,2024-01-08,Sneha Patil,East,Chair,Furniture,5,2000,5,UPI,9500.0
4,1005,2024-01-09,Arjun Rao,West,Monitor,Electronics,2,15000,8,Debit Card,27600.0

In [19]:
# agg
# region wise revenue
sales.groupby('Region')['Total_Amount'].sum()

Region
East       9500.0
North     27000.0
South     24000.0
West     132100.0
Name: Total_Amount, dtype: float64

In [20]:
# category wise sales
sales.groupby('Category')['Price'].mean()

Category
Electronics    33333.333333
Furniture       5000.000000
Name: Price, dtype: float64

In [21]:
sales.head()

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Price,Discount,Payment_Mode,Total_Amount
0,1001,2024-01-05,Amit Sharma,West,Laptop,Electronics,2,55000,5,UPI,104500.0
1,1002,2024-01-06,Priya Verma,North,Phone,Electronics,1,30000,10,Credit Card,27000.0
2,1003,2024-01-07,Rahul Jain,South,Table,Furniture,3,8000,0,Cash,24000.0
3,1004,2024-01-08,Sneha Patil,East,Chair,Furniture,5,2000,5,UPI,9500.0
4,1005,2024-01-09,Arjun Rao,West,Monitor,Electronics,2,15000,8,Debit Card,27600.0

In [22]:
order.head()

,order_id,order_date,customer_id,product,category,price,quantity,city,delivery_days,Revenue
0,5001,2024-02-01,C001,Laptop,Electronics,55000,1,Nagpur,3,55000
1,5002,2024-02-02,C002,Phone,Electronics,30000,2,Mumbai,5,60000
2,5003,2024-02-03,C003,Shoes,Fashion,4000,3,Pune,4,12000
3,5004,2024-02-04,C001,Watch,Fashion,7000,1,Nagpur,2,7000
4,5005,2024-02-05,C004,Tablet,Electronics,25000,1,Delhi,6,25000

#  Concatenate and merge dataframe joins

In [27]:
pd.concat([sales,order],axis=0) #vertical row level top on top

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Price,Discount,Payment_Mode,...,order_id,order_date,customer_id,product,category,price,quantity,city,delivery_days,Revenue
0,1001.0,2024-01-05,Amit Sharma,West,Laptop,Electronics,2.0,55000.0,5.0,UPI,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1002.0,2024-01-06,Priya Verma,North,Phone,Electronics,1.0,30000.0,10.0,Credit Card,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1003.0,2024-01-07,Rahul Jain,South,Table,Furniture,3.0,8000.0,0.0,Cash,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004.0,2024-01-08,Sneha Patil,East,Chair,Furniture,5.0,2000.0,5.0,UPI,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1005.0,2024-01-09,Arjun Rao,West,Monitor,Electronics,2.0,15000.0,8.0,Debit Card,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5001.0,2024-02-01,C001,Laptop,Electronics,55000.0,1.0,Nagpur,3.0,55000.0
1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5002.0,2024-02-02,C002,Phone,Electronics,30000.0,2.0,Mumbai,5.0,60000.0
2,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5003.0,2024-02-03,C003,Shoes,Fashion,4000.0,3.0,Pune,4.0,12000.0
3,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5004.0,2024-02-04,C001,Watch,Fashion,7000.0,1.0,Nagpur,2.0,7000.0
4,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5005.0,2024-02-05,C004,Tablet,Electronics,25000.0,1.0,Delhi,6.0,25000.0

In [29]:
pd.concat([sales,order],axis=1) #horizonatal column side by side

,Order_ID,Order_Date,Customer_Name,Region,Product,Category,Quantity,Price,Discount,Payment_Mode,...,order_id,order_date,customer_id,product,category,price,quantity,city,delivery_days,Revenue
0,1001,2024-01-05,Amit Sharma,West,Laptop,Electronics,2,55000,5,UPI,...,5001,2024-02-01,C001,Laptop,Electronics,55000,1,Nagpur,3,55000
1,1002,2024-01-06,Priya Verma,North,Phone,Electronics,1,30000,10,Credit Card,...,5002,2024-02-02,C002,Phone,Electronics,30000,2,Mumbai,5,60000
2,1003,2024-01-07,Rahul Jain,South,Table,Furniture,3,8000,0,Cash,...,5003,2024-02-03,C003,Shoes,Fashion,4000,3,Pune,4,12000
3,1004,2024-01-08,Sneha Patil,East,Chair,Furniture,5,2000,5,UPI,...,5004,2024-02-04,C001,Watch,Fashion,7000,1,Nagpur,2,7000
4,1005,2024-01-09,Arjun Rao,West,Monitor,Electronics,2,15000,8,Debit Card,...,5005,2024-02-05,C004,Tablet,Electronics,25000,1,Delhi,6,25000

In [32]:
sales.columns = sales.columns.str.lower()
sales.columns

Index(['order_id', 'order_date', 'customer_name', 'region', 'product',
       'category', 'quantity', 'price', 'discount', 'payment_mode',
       'total_amount'],
      dtype='object')

In [34]:
# merge 

pd.merge(sales,order,how='inner',on='order_id')

Empty DataFrame
Columns: [order_id, order_date_x, customer_name, region, product_x, category_x, quantity_x, price_x, discount, payment_mode, total_amount, order_date_y, customer_id, product_y, category_y, price_y, quantity_y, city, delivery_days, Revenue]
Index: []

In [35]:
pd.merge(order,sales,how='left',on='order_id')

,order_id,order_date_x,customer_id,product_x,category_x,price_x,quantity_x,city,delivery_days,Revenue,order_date_y,customer_name,region,product_y,category_y,quantity_y,price_y,discount,payment_mode,total_amount
0,5001,2024-02-01,C001,Laptop,Electronics,55000,1,Nagpur,3,55000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5002,2024-02-02,C002,Phone,Electronics,30000,2,Mumbai,5,60000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5003,2024-02-03,C003,Shoes,Fashion,4000,3,Pune,4,12000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5004,2024-02-04,C001,Watch,Fashion,7000,1,Nagpur,2,7000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5005,2024-02-05,C004,Tablet,Electronics,25000,1,Delhi,6,25000,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
pd.merge(order,sales,how='right',on='order_id')

,order_id,order_date_x,customer_id,product_x,category_x,price_x,quantity_x,city,delivery_days,Revenue,order_date_y,customer_name,region,product_y,category_y,quantity_y,price_y,discount,payment_mode,total_amount
0,1001,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-05,Amit Sharma,West,Laptop,Electronics,2,55000,5,UPI,104500.0
1,1002,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-06,Priya Verma,North,Phone,Electronics,1,30000,10,Credit Card,27000.0
2,1003,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-07,Rahul Jain,South,Table,Furniture,3,8000,0,Cash,24000.0
3,1004,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-08,Sneha Patil,East,Chair,Furniture,5,2000,5,UPI,9500.0
4,1005,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-09,Arjun Rao,West,Monitor,Electronics,2,15000,8,Debit Card,27600.0

In [41]:
pd.merge(order,sales,how='outer',on='order_id')

,order_id,order_date_x,customer_id,product_x,category_x,price_x,quantity_x,city,delivery_days,Revenue,order_date_y,customer_name,region,product_y,category_y,quantity_y,price_y,discount,payment_mode,total_amount
0,1001,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-05,Amit Sharma,West,Laptop,Electronics,2.0,55000.0,5.0,UPI,104500.0
1,1002,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-06,Priya Verma,North,Phone,Electronics,1.0,30000.0,10.0,Credit Card,27000.0
2,1003,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-07,Rahul Jain,South,Table,Furniture,3.0,8000.0,0.0,Cash,24000.0
3,1004,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-08,Sneha Patil,East,Chair,Furniture,5.0,2000.0,5.0,UPI,9500.0
4,1005,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-09,Arjun Rao,West,Monitor,Electronics,2.0,15000.0,8.0,Debit Card,27600.0
5,5001,2024-02-01,C001,Laptop,Electronics,55000.0,1.0,Nagpur,3.0,55000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5002,2024-02-02,C002,Phone,Electronics,30000.0,2.0,Mumbai,5.0,60000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5003,2024-02-03,C003,Shoes,Fashion,4000.0,3.0,Pune,4.0,12000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5004,2024-02-04,C001,Watch,Fashion,7000.0,1.0,Nagpur,2.0,7000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5005,2024-02-05,C004,Tablet,Electronics,25000.0,1.0,Delhi,6.0,25000.0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
# Merging data

merged = pd.merge(sales,order,left_on="customer_name",right_on="customer_id",how="inner")

In [43]:
merged

Empty DataFrame
Columns: [order_id_x, order_date_x, customer_name, region, product_x, category_x, quantity_x, price_x, discount, payment_mode, total_amount, order_id_y, order_date_y, customer_id, product_y, category_y, price_y, quantity_y, city, delivery_days, Revenue]
Index: []

[0 rows x 21 columns]

# Export Clean data

In [44]:
sales.to_csv('clean_sales.csv',index=False)

In [45]:
order.to_excel('clean_order.xlsx',index=False)

In [46]:
emp.to_json('clean_json.json',orient='records')

In [ ]:
# load into postgresql using sqlalchemy

from sqlalchemy from create_engine

engine = create_engine("postgresql://username:MALI8261@localhost:5432/sales_db")


sales.to_sql('sales',engine,if_exists='replace',index=False)
order.to_sql('order',engine,if_exists='replace',index= False)
emp.to_sql('order',engine,if_exists='replace',index=False)

print('Connections successful')